<div class="container p-3 mt-3 mb-4" id="container">
	<div class="row d-flex justify-content-center">
		
		<div class="row mb-4 d-flex justify-content-center">
			<a href="/prehistoria" class="btn col-6 btn-danger">Pré-História</a>
		</div>

		<div class="row mb-4 d-flex justify-content-center">
			<a href="/antiga" class="btn col-6 btn-warning">Idade Antiga</a>
		</div>

		<div class="row mb-4 d-flex justify-content-center">
			<a href="/media" class="btn col-6 btn-primary">Idade Média</a>
		</div>

		<div class="row mb-4 d-flex justify-content-center">
			<a href="/moderna" class="btn col-6 btn-success">Idade Moderna</a>
		</div>

		<div class="row mb-4 d-flex justify-content-center">
			<a href="/contemporanea" class="btn col-6 btn-info">Idade Contemporânea</a>
		</div>

	</div>
</div>