<!-- CAROUSEL -->
<div id="carousel" class="container-fluid mt-5">
	<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">

		<div class="carousel-inner">

			<?php foreach ($this->view->carousel as $key => $noticia) { ?>

			<?php if ($key == 0) { ?>
			<div class="carousel-item active">
				<div class="row">
					
					<div class="col-md-6 d-flex justify-content-center">
						<div class="col-10"> <img src="<?= $noticia['capa'] ?>" class="carousel-image img-fluid"> </div>
					</div>

					<div class="col-md-6 d-flex">
						<div class="carousel-card align-self-center col-lg-10">
							<h1 class="text-center"><?= $noticia['titulo'] ?></h1>
							<p class="text-center"><?= $noticia['descricao'] ?></p>
							<div class="d-flex justify-content-center"><a href="/noticia?id=<?= $noticia['id'] ?>" class="btn btn-light">Leia Mais</a></div>
						</div>
					</div>

				</div>
			</div>
			<?php } else { ?>
			<div class="carousel-item">
				<div class="row">
					
					<div class="col-md-6 col-12 d-flex justify-content-center">
						<div class="col-10"> <img src="<?= $noticia['capa'] ?>" class="carousel-image img-fluid"> </div>
					</div>

					<div class="col-md-6 d-flex">
						<div class="carousel-card align-self-center col-lg-10">
							<h1 class="text-center"><?= $noticia['titulo'] ?></h1>
							<p class="text-center"><?= $noticia['descricao'] ?></p>
							<div class="d-flex justify-content-center"><a href="/noticia?id=<?= $noticia['id'] ?>" class="btn btn-light">Leia Mais</a></div>
						</div>
					</div>

				</div>
			</div>
			<?php } ?>

			<?php } ?>
		</div>

		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
			<i id="prev" class="fa-solid fa-circle-arrow-left fa-3x"></i>
		</button>

		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
			<i id="next" class="fa-solid fa-circle-arrow-right fa-3x"></i>
		</button>

	</div>
</div>

<!-- ÚLTIMAS NOTÍCIAS -->
<div id="last" class="container">
	<div class="col-lg-4"> <h1 id="title">Últimas Artigos</h1> </div>

	<div class="row pt-3 justify-content-around">

		<?php foreach ($this->view->noticias as $key => $noticia) { ?>
			<a href="/noticia?id=<?= $noticia['id'] ?>" class="last-card col-lg-3">
				<div class="col-lg-12"> <h2><?= $noticia['titulo'] ?></h2> </div>

				<div class="col-lg-12"> <img src="<?= $noticia['capa'] ?>" class="img-fluid"> </div>

				<div class="col-lg-12"> <p class="text-center"><?= $noticia['descricao'] ?></p> </div>
			</a>
		<?php } ?>

	</div>
</div>

<!-- ÚLTIMAS BIOGRAFIAS -->
<div id="last" class="container">
	<div class="col-lg-5"> <h1 id="title">Últimas Biografias</h1> </div>

	<div class="row pt-3 justify-content-around">

		<?php foreach ($this->view->biografias as $key => $biografia) { ?>
		<a href="/noticia?id=<?= $biografia['id'] ?>" class="last-card col-lg-3">
			<div class="col-lg-12"> <h2><?= $biografia['titulo'] ?></h2> </div>

			<div class="col-lg-12"> <img src="<?= $biografia['capa'] ?>" class="img-fluid"> </div>

			<div class="col-lg-12"> <p class="text-center"><?= $biografia['descricao'] ?></p> </div>
		</a>
		<?php } ?>

	</div>
</div>

<!-- FOOTER -->
<footer class="container-fluid">
	
	<div class="row d-flex" id="footer">
		
		<div class="col-md-3 col-12 align-self-center">
			<img src="Imagens/WHITE-ANCIENT.png" class="img-fluid">
		</div>

		<div class="col-md-3 col-lg-2 col-6">
			<h4>Company</h4>
			<ul class="navbar-nav">
				<li><a href="">Sobre</a></li>
				<li><a href="">Empregos</a></li>
				<li><a href="">Imprensa</a></li>
				<li><a href="">Novidade</a></li>
			</ul>
		</div>

		<div class="col-md-3 col-lg-2 col-6">
			<h4>Comunidade</h4>
			<ul class="navbar-nav">
				<li><a href="">Professores</a></li>
				<li><a href="">Jornalistas</a></li>
				<li><a href="">Desenvolvedores</a></li>
			</ul>
		</div>

		<div class="col-md-3 col-lg-2 col-12">
			<h4>Links úteis</h4>
			<ul class="navbar-nav">
				<li><a href="">Ajuda</a></li>
				<li><a href="">Referências Bibliográficas</a></li>
				<li><a href="">Caixa Postal</a></li>
			</ul>
		</div>

		<div class="col-md-12 col-lg-3 align-self-center">
			<p>&copy; Copyright 2000-2021 ANCIENT</p>
		</div>

	</div>

</footer>