<div class="container p-3 mt-3 mb-4" id="container">
	<div class="row d-flex justify-content-center">
		
		<!-- ÁREA DE PESQUISA -->
		<div class="row d-flex justify-content-center">

			<div class="col-12 col-md-7">
				<form action="/todosRegistros" method="get">
					<div class="input-group">

						<input name="dados" type="text" class="form-control" placeholder="Pesquisa por uma notícia">
						<div class="input-group-append">
							<button type="submit" class="btn btn-dark">
								<i class="fa-solid fa-magnifying-glass"></i>
							</button>
						</div>

					</div>
				</form>
			</div>
		</div>
		<!------------------------------------------------>

		<div class="row mt-3">

			<!-- CASO O REGISTRO NÃO SEJA ENCONTRADO -->
			<?php if (isset($_GET['erro']) && $_GET['erro'] == 'erro') { ?>
			<div class="row d-flex justify-content-center">
				<div class="d-flex justify-content-center col-12 col-md-9 col-lg-6">
					<h1 class="text-danger">Registro não encontrado!</h1>
				</div>
			</div>
			<?php } ?>
			<!------------------------------------------------>

			<!-- ÁREA DE EXIBIÇÃO DOS REGISTROS -->
			<?php if ($this->view->noticias != '') { foreach ($this->view->noticias as $key => $noticia) { ?>
			<div class="row d-flex justify-content-center">
				<div class="cartao col-12 col-md-9 col-lg-6">
					<h3> <?= $noticia['titulo'] ?> </h3>

					<img src="<?= $noticia['capa'] ?>" class="img-fluid">

					<p> <?= $noticia['descricao'] ?> </p>

					<a href="/noticia?id=<?= $noticia['id'] ?>" class="btn btn-light">Leia Mais!</a>
				</div>
			</div>

			<?php } ?>
			<!------------------------------------------------>
			
			<!-- ÁREA DE NAVEGAÇÃO -->
			<nav class="d-flex justify-content-center" aria-label="Page navigation example">
				<ul class="pagination">
					<li class="page-item"><a class="page-link" href="#">Primeira</a></li>
					
					<?php for ($i=1; $i <= $this->view->total_paginas; $i++) { ?>
					<li class="page-item"><a class="page-link" href="/fotos?pag=<?= $i ?>"> <?= $i ?> </a></li>
					<?php } ?>

					<li class="page-item"><a class="page-link" href="#">Última</a></li>
				</ul>
			</nav>
			<!------------------------------------------------>

			<?php } else { ?>
				<br><br><br><br><br><br><br>
			<?php } ?>

		</div>

	</div>
</div>