<div class="bg-success p-4">
	<h1>Crie uma notícia!</h1>

	<form action="/inserir_bio" method="post" enctype="multipart/form-data">
		
		<div class="row mb-3">
			<h4>Título:</h4>
			<input name="titulo" class="form-control" type="text" placeholder="Insira um Título">
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Capa:</h4>
			<input name="capa" class="form-control" type="file">
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Descrição:</h4>
			<textarea  name="descricao" class="form-control" type="text" placeholder="Insira uma Descrição Básica"></textarea>
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Conteúdo:</h4>
			<textarea name="conteudo" class="form-control" type="text" placeholder="Insira o Conteúdo"></textarea>
		</div>

		<div class="d-flex justify-content-end">
			<button type="submit" class="btn btn-dark btn-lg">Criar</button>
		</div>

	</form>
</div>