<div class="bg-warning p-4">
	<h1>Crie uma notícia!</h1>

	<form action="/inserir_noticia" method="post" enctype="multipart/form-data">
		
		<div class="row mb-3">
			<h4>Título:</h4>
			<input name="titulo" class="form-control" type="text" placeholder="Insira um Título">
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Capa:</h4>
			<input name="capa" class="form-control" type="file">
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Descrição:</h4>
			<textarea  name="descricao" class="form-control" type="text" placeholder="Insira uma Descrição Básica"></textarea>
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Conteúdo:</h4>
			<textarea name="conteudo" class="form-control" type="text" placeholder="Insira o Conteúdo"></textarea>
		</div>

		<div class="row mb-3">
			<div class="col-12"><h4>Classe e Idade:</h4></div>

			<div class="col-6 d-flex">
				<select name="classe" class="form-control mb-3">
					<option value="">--Selecione uma CLASSE--</option>
					<option value="mundo">Mundo</option>
					<option value="brasil">Brasil</option>
				</select>
			</div>

			<div class="col-6">
				<select name="idade" class="form-control">
					<option value="">--Selecione uma IDADE--</option>
					<option value="prehistoria">Pré-História</option>
					<option value="antiga">Idade Antiga</option>
					<option value="media">Idade Média</option>
					<option value="moderna">Idade Moderna</option>
					<option value="contemporanea">Idade Contemporânea</option>
				</select>
			</div>

		</div>

		<div class="d-flex justify-content-end">
			<button type="submit" class="btn btn-dark btn-lg">Criar</button>
		</div>

	</form>
</div>