<?php if ($this->view->biografias['id'] == $_GET['id']) { ?>

<div class="bg-info p-4">
	<h1>Edite a biografia!</h1>

	<form action="/editar_bio" method="post" enctype="multipart/form-data">
		
		<input name="id" class="form-control" type="hidden" value="<?= $_GET['id'] ?>">

		<div class="row mb-3">
			<h4>Título:</h4>
			<input name="titulo" class="form-control" type="text" placeholder="Insira um Título" value="<?= $this->view->biografias['titulo'] ?>">
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Capa:</h4>
			<input name="capa" class="form-control" type="file">
			<small class="avisos col-3 d-flex justify-content-center mt-2">Escolha a capa novamente</small>
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Descrição:</h4>
			<textarea name="descricao" class="form-control" type="text" placeholder="Insira uma Descrição Básica"><?= $this->view->biografias['descricao'] ?></textarea>
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Conteúdo:</h4>
			<textarea name="conteudo" class="form-control" type="text" placeholder="Insira o Conteúdo"><?= $this->view->biografias['conteudo'] ?></textarea>
		</div>

		<div class="d-flex justify-content-end">
			<button type="submit" class="btn btn-dark btn-lg">Editar</button>
		</div>

	</form>
</div>

<?php } ?>