<?php if ($this->view->noticias['id'] == $_GET['id']) { ?>

<div class="bg-info p-4">
	<h1>Edite a notícia!</h1>

	<form action="/editar_noticia" method="post" enctype="multipart/form-data">
		
		<input name="id" class="form-control" type="hidden" value="<?= $_GET['id'] ?>">

		<div class="row mb-3">
			<h4>Título:</h4>
			<input name="titulo" class="form-control" type="text" placeholder="Insira um Título" value="<?= $this->view->noticias['titulo'] ?>">
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Capa:</h4>
			<input name="capa" class="form-control" type="file">
			<small class="avisos col-3 d-flex justify-content-center mt-2">Escolha a capa novamente</small>
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Descrição:</h4>
			<textarea name="descricao" class="form-control" type="text" placeholder="Insira uma Descrição Básica"><?= $this->view->noticias['descricao'] ?></textarea>
		</div>

		<hr>

		<div class="row mb-3">
			<h4>Conteúdo:</h4>
			<textarea name="conteudo" class="form-control" type="text" placeholder="Insira o Conteúdo"><?= $this->view->noticias['conteudo'] ?></textarea>
		</div>

		<div class="row mb-3">
			<div class="col-12"><h4>Classe e Idade:</h4></div>

			<div class="col-6">
				<select name="classe" class="form-control">
					<option value=""><small>Escolha a classe novamente</small></option>
					<option value="mundo">Mundo</option>
					<option value="brasil">Brasil</option>
				</select>
			</div>

			<div class="col-6">
				<select name="idade" class="form-control">
					<option value=""><small>Escolha a idade novamente</small></option>
					<option value="prehistoria">Pré-História</option>
					<option value="antiga">Idade Antiga</option>
					<option value="media">Idade Média</option>
					<option value="moderna">Idade Moderna</option>
					<option value="contemporanea">Idade Contemporânea</option>
				</select>
			</div>

			<div class="col-6 mt-2">
				<small class="avisos">Escolha a classe novamente</small>
			</div>

			<div class="col-6 mt-2">
				<small class="avisos">Escolha a idade novamente</small>
			</div>

		</div>

		<div class="d-flex justify-content-end">
			<button type="submit" class="btn btn-dark btn-lg">Editar</button>
		</div>

	</form>
</div>

<?php } ?>