<!DOCTYPE html>
<html>
<head id="html">

	<!-- TÍTULO -->
	<title>Ancient</title>

	<!-- META TAGS -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="CSS/estilo.css">

	<!-- BOOTSTRAP CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

	<!-- BOOTSTRAP JS -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

	<!-- ICON DO SITE -->
	<link rel="icon" href="Imagens/icon.png">

	<!-- Font Awesome - Icons -->
	<script src="https://kit.fontawesome.com/5d9c2ca835.js" crossorigin="anonymous"></script>

</head>

<body id="body">

	<!-- BARRA DE NAVEGAÇÃO -->
	<nav id="nav" class="navbar navbar-expand-lg">
		<div class="container-fluid">

			<a class="navbar-brand" href="/"> <img src="IMAGENS/logo.png" class="img-fluid"> </a>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">

				<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active text-white" aria-current="page" href="#">Home</a>
					</li>

					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Idades</a>
						<ul class="dropdown-menu">
						<li><a class="dropdown-item" href="#">Pré-História</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item" href="#">Idade Antiga</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item" href="#">Idade Média</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item" href="#">Idade Moderna</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item" href="#">Idade Contemporânea</a></li>
						</ul>
					</li>

					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Classe</a>
						<ul class="dropdown-menu">
						<li><a class="dropdown-item" href="#">Mundo</a></li>
						<li><hr class="dropdown-divider"></li>
						<li><a class="dropdown-item" href="#">Brasil</a></li>
						</ul>
					</li>

					<li class="nav-item">
						<a class="nav-link active text-white" aria-current="page" href="#">Fotos</a>
					</li>

					<li class="nav-item">
						<a class="nav-link active text-white" aria-current="page" href="#">Biografias</a>
					</li>
				</ul>

				<form id="search" class="d-flex p-lg-3" role="search">
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-light" type="submit">Search</button>
				</form>

			</div>

		</div>
	</nav>

	<?php $this->content() ?>

</body>
</html>